ALTER TABLE "ConfiguracaoSistema"
ADD COLUMN "dtfClienteMetro" DECIMAL(10,2) NOT NULL DEFAULT 150,
ADD COLUMN "dtfRevendedorMetro" DECIMAL(10,2) NOT NULL DEFAULT 100,
ADD COLUMN "dtfAbaixo10CmMetro" DECIMAL(10,2) NOT NULL DEFAULT 200;
